server.port=8080

# Sửa lại username và password cho đúng với PostgreSQL của bạn
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_learning_db
spring.datasource.username=postgres
spring.datasource.password=kt123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
gemini.api.key=AIzaSyAo34AK63H2ie5o-ysx0ZAu5XVFwBVUjF8