// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
        
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzhp8-qvaDGwcvUXyh15bD4RfMAIK2Ab8',
    appId: '1:152003370954:web:90762f603c4d7d6d9b3933',
    messagingSenderId: '152003370954',
    projectId: 'ai-learning-app-b8439',
    authDomain: 'ai-learning-app-b8439.firebaseapp.com',
    storageBucket: 'ai-learning-app-b8439.firebasestorage.app',
    measurementId: 'G-C3GHZTWS70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCDzHp1hMZRF3IW1_3xH5wDHGb-7fRmg4',
    appId: '1:152003370954:android:34cf8d98bd011b189b3933',
    messagingSenderId: '152003370954',
    projectId: 'ai-learning-app-b8439',
    storageBucket: 'ai-learning-app-b8439.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwbrCJXCID8Dt7lvEtDnENr9-rdflxDdc',
    appId: '1:152003370954:ios:343562b301ec30bd9b3933',
    messagingSenderId: '152003370954',
    projectId: 'ai-learning-app-b8439',
    storageBucket: 'ai-learning-app-b8439.firebasestorage.app',
    iosBundleId: 'com.example.aiLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwbrCJXCID8Dt7lvEtDnENr9-rdflxDdc',
    appId: '1:152003370954:ios:343562b301ec30bd9b3933',
    messagingSenderId: '152003370954',
    projectId: 'ai-learning-app-b8439',
    storageBucket: 'ai-learning-app-b8439.firebasestorage.app',
    iosBundleId: 'com.example.aiLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzhp8-qvaDGwcvUXyh15bD4RfMAIK2Ab8',
    appId: '1:152003370954:web:6fd09324e1655a509b3933',
    messagingSenderId: '152003370954',
    projectId: 'ai-learning-app-b8439',
    authDomain: 'ai-learning-app-b8439.firebaseapp.com',
    storageBucket: 'ai-learning-app-b8439.firebasestorage.app',
    measurementId: 'G-V8ZFZXDQLP',
  );
}
